FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    php-fpm \
    php-mysql \
    curl \
    mariadb-client \
    php-curl \
    php-xml \
    php-json \
    php-mbstring \
    && rm -rf /var/lib/apt/lists/*
